### ISSUE TITLE
Add projects from "Built With Elm"?

### ISSUE THREAD

**Issue by jvoigtlaender** [hakonrossebo/migrating-existing-projects-to-current-version-of-elm#3]
A natural place for looking for many more Elm apps, of which quite a few are not yet updated for 0.17: http://builtwithelm.co/

**Comment by hakonrossebo** [comment]
Thanks - I'll go through the projects listed there.

**Comment by hakonrossebo** [comment]
Added all projects from builtwithelm

**Comment by jvoigtlaender** [comment]
Cool!
